[package]
name = "rtv"
version = "1.2.0"
edition = "2021"
authors = ["foxcirc"]
description = "For when you just wanna run a future"
keywords = ["async", "futures", "simple", "io"]
categories = ["asynchronous"]
repository = "https://github.com/Foxcirc/rtv"
readme = "readme.md"
license = "MIT"

[dependencies]

