[package]
name = "rtv"
version = "2.0.1"
edition = "2021"
authors = ["foxcirc"]
description = "Minimal HTTP/S client that supports nonblocking and streaming requests using mio."
keywords = ["http", "client", "simple", "nonblocking", "mio"]
categories = ["web-programming", "web-programming::http-client"]
repository = "https://github.com/Foxcirc/rtv"
readme = "readme.md"
license = "MIT"

[lib]
doctest = false

[features]
default = ["tls"]
tls = ["rustls", "webpki-roots"]
json = ["serde_json"]

[dependencies]
dns-parser   = { version = "0.8.0" }
mio          = { version = "0.8.*", features = ["net", "os-poll"] }
rustls       = { version = "0.21.*", optional = true }
webpki-roots = { version = "0.23.*", optional = true }
serde_json   = { version = "1.0.*", optional = true }
# chunked_transfer = "1.4.1"
chunked_transfer = { path = "dependencies/chunked-transfer" }
httparse = "1.8.0"
