[package]
name = "rtv"
version = "2.0.0"
edition = "2021"
authors = ["foxcirc"]
description = "Minimal HTTP/S client that supports nonblocking and streaming requests using mio."
keywords = ["http", "client", "simple", "nonblocking", "streaming"]
categories = ["web-programming", "web-programming::http-client"]
repository = "https://github.com/Foxcirc/rtv"
readme = "readme.md"
license = "MIT"

[lib]
doctest = false

[dependencies]
dns-parser = "0.8.0"
mio = { version = "0.8.8", features = ["net", "os-poll"] }
rustls = "0.21.1"
webpki-roots = "0.23.1"

