[package]
name = "rtv"
version = "0.1.0"
edition = "2021"
authors = ["foxcirc"]
description = "For when you just wanna run a future"
keywords = ["async", "futures", "simple", "io"]
categories = ["asynchronous"]

[dependencies]


